/*
 Adform.Bootstrap.js, version 2.1.147091

 Copyright Adform
 http://www.adform.com

 Date: 2012-06-28
*/
(function(f,g,d){f.Log||(f.Log={Host:f.host,sendEvent:function(f,i,e){try{var h=[];h.push(this.Host);h.push("/Serving/JsLog/?src=");h.push(encodeURIComponent(f));h.push("&severity=");h.push(encodeURIComponent(i));h.push("&msg=");h.push(encodeURIComponent(e));(g.Image?new Image(1,1):d.createElement("img")).src=h.join("")}catch(b){}}})})(Adform=window.Adform||{},window,document);
(function(f,g,d){function k(){if(e)return e;if(this instanceof k){this.banners={};this.compoundBanners={};try{d.body||d.write("<html><body></body></html>")}catch(a){}var c=navigator,b=screen,f=c.browserLanguage||c.language||0,c=c.systemLanguage||f,h=b?b.width+"X"+b.height:0,b=b?b.colorDepth:0,g=this.getFlashVersion(),i=this.getJSVersion(),m=this.getCT(),q=this.getCPU(),n=this.getWin(),r=50*Math.round(n.w/50),n=50*Math.round(n.h/50),s=this.hasIframeSanbox();this.settings=[escape(c),escape(f),h,g,r,
n,b,i,m,q,s].join("|")}else return e=new k}if(!f.ADFBannerUtils){var i=-1,e,h=0,b=k.prototype;b.getCompoundBannerInfo=function(a){return this.compoundBanners["c"+a]||null};b.addNewBanner=function(a,c){this.banners[a]={id:a,type:c}};b.addBannerAttribute=function(a,c,b){(a=this.banners[a])&&(a[c]=b)};b.getTagID=function(){return++h+"x"};b.getJSVersion=function(){try{d.write('<span id="ADFtemp"></span>');for(var a=1;10>a;a++){var c=d.createElement("script");c.setAttribute("language","javascript1."+a);
c.text="ADFJSVersion="+(a+1)+";";try{d.getElementById("ADFtemp").appendChild(c)}catch(b){}}try{d.getElementById("ADFtemp").parentNode.removeChild(d.getElementById("ADFtemp"))}catch(e){}return"undefined"!=typeof ADFJSVersion?ADFJSVersion:1}catch(f){}};b.getFlashVersion=function(){if(-1==i){var a=navigator.plugins,c=navigator.mimeTypes,b=g.ActiveXObject,e=16,f,a=a&&a["Shockwave Flash"]&&(!c||!c["application/x-shockwave-flash"]||c["application/x-shockwave-flash"].enabledPlugin)&&a["Shockwave Flash"].description||
"";if(!a&&b)for(;6<=e--;)try{f=new b("ShockwaveFlash.ShockwaveFlash."+e);6==e&&(f.AllowScriptAccess="always",a="WIN 6.0.21.0");try{a=f.GetVariable("$version").replace(/,/g,".")}catch(d){}break}catch(h){}i=parseFloat(a.replace(/^.*?(\d+[\.,].*$)/,"$1"))||0}return i};b.getWin=function(){var a=d.documentElement,c=d.body;return{w:g.innerWidth||a&&a.clientWidth||c&&c.clientWidth,h:g.innerHeight||a&&a.clientHeight||c&&c.clientHeight}};b.getCT=function(){var a={lan:"1",modem:"2"},c="3";try{d.body.addBehavior&&
(d.body.addBehavior("#default#clientCaps"),c=d.body.connectionType.toLowerCase(),c="undefined"!=typeof a[c]?a[c]:c)}catch(b){}return c};b.getCPU=function(){return navigator.cpuClass?{x86:1,"68k":2,PPC:3,Alpha:4,Arm:5,Other:6}[navigator.cpuClass]||8:7};b.getSettings=function(){return this.settings};b.fireTargAdPixel=function(a){this.TargAd||(this.TargAd={});this.TargAd.gmtr=Math.floor(9999999999*Math.random());this.TargAd.gmttzd=(new Date).getTimezoneOffset();a=a.replace("{gmtr}",this.TargAd.gmtr);
a=a.replace("{gmttzd}",this.TargAd.gmttzd);this.TargAd.gmtimg||(this.TargAd.gmtimg="undefined"==typeof g.Image?d.createElement("img"):new g.Image,this.TargAd.gmtimg.src=a)};b.registerImpression=function(a){if(!a.registered){var c=a.adfserve.indexOf(";hid=2");if(-1<c&&(a.adfserve[c]=";hid=1",0>a.adfserve.join("").indexOf(";rotseqno="))){var b=this.banners[a.tagId];b&&a.adfserve.splice(c+1,0,";rotseqno="+b.rotseqno)}c=d.createElement("script");c.src=a.adfserve.join("");d.body.appendChild(c);a.registered=
!0}};b.addCompoundBannerInfo=function(a,c){this.compoundBanners["c"+a]="r"+c};b.setBannerRegisteredStatus=function(a){try{this.addBannerAttribute(a,"registered",1),f.ADFEventsInstance&&f.ADFEventsInstance.register(this.banners[a])}catch(c){}};b.hasIframeSanbox=function(){try{return g.top.document.getElementById,0}catch(a){return 1}};f.ADFBannerUtils=k.getInstance=k;f.ADFUtilInstance=k();b.ADFCreateObjectCallback=function(a,c){return function(){c.apply(a,arguments)}};b.eventRegister=function(a,c,b,
e){b.addEventListener?b.addEventListener(a,this.ADFCreateObjectCallback(eval(e),eval(c)),!1):b.attachEvent&&b.attachEvent("on"+a,this.ADFCreateObjectCallback(eval(e),eval(c)),!1)};b.getPosition=function(a){try{var c={};c.y=a.offsetTop;c.x=a.offsetLeft;for(var b;null!=a.offsetParent;)b=a.offsetParent,c.y+=b.offsetTop,c.x+=b.offsetLeft,a=b;return c}catch(e){}};b.getScrollXY=function(){try{var a={x:0,y:0};if("number"==typeof g.pageYOffset)a.y=g.pageYOffset,a.x=g.pageXOffset;else if(d.body&&(d.body.scrollLeft||
d.body.scrollTop))a.y=d.body.scrollTop,a.x=d.body.scrollLeft;else if(d.documentElement&&(d.documentElement.scrollLeft||d.documentElement.scrollTop))a.y=d.documentElement.scrollTop,a.x=d.documentElement.scrollLeft;return a}catch(b){}};b.getBrowser=function(){try{if(-1!=navigator.appVersion.indexOf("MSIE")&&0>navigator.userAgent.indexOf("Opera"))return"MSIE";if(-1!=navigator.userAgent.indexOf("Safari"))return"Safari";if(-1!=navigator.userAgent.indexOf("Opera"))return"Opera";if(-1!=navigator.appName.indexOf("Netscape"))return-1!=
navigator.product.indexOf("Gecko")&&(-1!=navigator.vendor.indexOf("Firefox")||-1!=navigator.userAgent.indexOf("Firefox"))?"Firefox":"Netscape"}catch(a){}}}})(Adform=window.Adform||{},window,document);
(function(f,g,d){f.ADFBanner=function(){try{var g=this;g.registered=!0;var i="",e="",h="",b=null;if(f.ADFBannerParams)var a=f.ADFBannerParams.shift(),e=a.URL,h=a.CREFURL,b=a.BN;else e=f.ADFBannerData.URL,h=f.ADFBannerData.CREFURL,b=f.ADFBannerData.BN;"undefined"==typeof f.ADFIframe?this.iframeMode=0:this.iframeMode=1;this.utilsInstance=f.ADFBannerUtils.getInstance();var c=this.utilsInstance.getTagID();this.tagId=c;this.utilsInstance.addNewBanner(c,this.iframeMode);-1!=e.indexOf("OOBClickTrack=")&&
(i=e.split(";OOBClickTrack=")[1],null!=i&&(i=encodeURIComponent(i)),e=e.split(";OOBClickTrack=")[0],this.utilsInstance.addBannerAttribute(c,"msn",1));var o=this.utilsInstance.getCompoundBannerInfo(b);g.adfserve=[e,";js=1",";adfxid=",c];"prerender"==d.webkitVisibilityState&&(g.adfserve.push(";hid=2"),g.registered=!1);g.adfserve.push(";"+Math.floor(11E3*Math.random()));g.adfserve.push(";set="+this.utilsInstance.getSettings());o&&g.adfserve.push(o.replace("r",";rotseqno="));""!=i&&g.adfserve.push(";OOBClickTrack="+
i);"undefined"!=typeof f.CDNHost&&g.adfserve.push(";cdnhost="+encodeURIComponent(f.CDNHost));g.adfserve.push("&CREFURL="+h);d.write('<script type="text/javascript" src="'+g.adfserve.join("")+'"><\/script>');try{d.addEventListener("webkitvisibilitychange",function(){d.webkitVisibilityState!="prerender"&&!g.registered&&g.utilsInstance.registerImpression(g)},!1)}catch(l){}}catch(j){}};new f.ADFBanner})(Adform=window.Adform||{},window,document);
(function(f,g,d){function k(e,h,b,a,c){try{this.notifyAboutEvent.apply(this,[].slice.call(arguments,0))}catch(i){}var l=(new Date).getTime()-this.InitTime,l=0<l?Math.round(l/1E3):0,l=3600<l?3600:l,j=f.ADFBannerUtils&&f.ADFBannerUtils.getInstance();if(j=j&&j.banners&&j.banners[e]){for(var l=[{key:"?bn=",value:j.bn},{key:"&event=",value:h},{key:"&time=",value:l},{key:"&banner=",value:j.ban},{key:"&innerbanner=",value:j.innerban},{key:"&asset=",value:b},{key:"&name=",value:a},{key:"&imprid=",value:j.unloadID},
{key:"&rnd=",value:Math.floor(1E9*Math.random())},{key:"",value:c}],j=this.Host+"/Serving/Event/",k=0,p=l.length;k<p;++k){var m=l[k];if(m.value||!isNaN(m.value))j+=m.key+m.value}(g.Image?new g.Image(1,1):d.createElement("img")).src=j;this.IsDebugConsoleEnabled&&this.debugElem&&(this.debugElem.value="NEW EVENT: "+j+"\n"+this.debugElem.value)}}if(!f.Events){var i={Initialized:!1,InitTime:0,IsDebugConsoleEnabled:!1,Host:f.host||("https:"==d.location.protocol?"https://":"http://")+"track.adform.net",
wnd:g,Img:"undefined"==typeof g.Image?d.createElement("img"):new g.Image(1,1),debugElem:null,callbacks:{},Initialize:function(){if(!this.Initialized){this.Initialized=!0;this.InitTime=(new Date).getTime();this.sendEvent=k;var e=f.ADFBannerUtils&&f.ADFBannerUtils.getInstance(),e=e&&e.banners,d;for(d in e)(function(b,a){"function"!=typeof g[a]&&(g[a]=function(a,e){var d=e.split("#|#")[1];f.Events.sendEvent(b,d)})})(d,"FSCommandID"+d)}},showEventsDebugConsole:function(){if(!this.IsDebugConsoleEnabled){var e=
this.wnd.document,d=e.createElement("div");d.innerHTML='<br/><br/><table align="center" style="background:#EEEEEE; color:#000000;border: #EEEEEE 1px solid;"><tr><th align="center"><b>Send Event - Debug Console</b></th></tr><tr><td align="center"><textarea name="debugConsole" id="debugConsole" rows="14" cols="120" readonly style="font-size:12px;background:#EEEEEE"></textarea><br/></td></tr></table>';e.insertAdjacentHTML?e.insertAdjacentHTML("BeforeEnd",d.innerHTML):e.body.insertBefore(d,e.body.lastChild);
this.debugElem=e.getElementById("debugConsole");this.IsDebugConsoleEnabled=!0}},registerCallback:function(e,d){if("function"==typeof e){var b=this.callbacks,a="CB_"+e;Object.prototype.hasOwnProperty.call(b,a)||(b[a]=function(){e.apply(d||g,arguments)})}},unregisterCallback:function(e){if("function"==typeof e){var d=this.callbacks,e="CB_"+e;Object.prototype.hasOwnProperty.call(d,e)&&delete d[e]}},notifyAboutEvent:function(){var d=[].slice.call(arguments,0),f=this.callbacks,b;for(b in f)Object.prototype.hasOwnProperty.call(f,
b)&&f[b].apply(null,d)}};f.Events=i;f.ADFEvents2||(f.ADFEvents2={sendEvent:i.sendEvent})}})(Adform=window.Adform||{},window,document);